/*
_comments - Bool; [optional];
 Set this flag to true to prevent removing comments from @text ( minxml and mincss functions only. )

 Examples:
 vkbeautify.xml(text); // pretty print XML
 vkbeautify.json(text, 4 ); // pretty print JSON
 vkbeautify.css(text, '. . . .'); // pretty print CSS
 vkbeautify.sql(text, '----'); // pretty print SQL

 vkbeautify.xmlmin(text, true);// minify XML, preserve comments
 vkbeautify.jsonmin(text);// minify JSON
 vkbeautify.cssmin(text);// minify CSS, remove comments ( default )
 vkbeautify.sqlmin(text);// minify SQL

*/
(function(){function k(e){var d="    ";if(isNaN(parseInt(e)))d=e;else switch(e){case 1:d=" ";break;case 2:d="  ";break;case 3:d="   ";break;case 4:d="    ";break;case 5:d="     ";break;case 6:d="      ";break;case 7:d="       ";break;case 8:d="        ";break;case 9:d="         ";break;case 10:d="          ";break;case 11:d="           ";break;case 12:d="            "}e=["\n"];for(ix=0;ix<100;ix++)e.push(e[ix]+d);return e}function i(){this.step="\t";this.shift=k(this.step)}i.prototype.xml=function(e,
d){for(var a=e.replace(/>\s{0,}</g,"><").replace(/</g,"~::~<").replace(/\s*xmlns\:/g,"~::~xmlns:").replace(/\s*xmlns\=/g,"~::~xmlns=").split("~::~"),i=a.length,f=!1,h=0,b="",c=0,j=d?k(d):this.shift,c=0;c<i;c++)if(a[c].search(/<!/)>-1){if(b+=j[h]+a[c],f=!0,a[c].search(/--\>/)>-1||a[c].search(/\]>/)>-1||a[c].search(/!DOCTYPE/)>-1)f=!1}else a[c].search(/--\>/)>-1||a[c].search(/\]>/)>-1?(b+=a[c],f=!1):/^<\w/.exec(a[c-1])&&/^<\/\w/.exec(a[c])&&/^<[\w:\-\.\,]+/.exec(a[c-1])==/^<\/[\w:\-\.\,]+/.exec(a[c])[0].replace("/",
"")?(b+=a[c],f||h--):a[c].search(/<\w/)>-1&&a[c].search(/<\//)==-1&&a[c].search(/\/>/)==-1?b=!f?b+=j[h++]+a[c]:b+=a[c]:a[c].search(/<\w/)>-1&&a[c].search(/<\//)>-1?b=!f?b+=j[h]+a[c]:b+=a[c]:a[c].search(/<\//)>-1?b=!f?b+=j[--h]+a[c]:b+=a[c]:a[c].search(/\/>/)>-1?b=!f?b+=j[h]+a[c]:b+=a[c]:b+=a[c].search(/<\?/)>-1?j[h]+a[c]:a[c].search(/xmlns\:/)>-1||a[c].search(/xmlns\=/)>-1?j[h]+a[c]:a[c];return b[0]=="\n"?b.slice(1):b};i.prototype.json=function(e,d){d=d?d:this.step;return typeof JSON==="undefined"?
e:typeof e==="string"?JSON.stringify(JSON.parse(e),null,d):typeof e==="object"?JSON.stringify(e,null,d):e};i.prototype.css=function(e,d){for(var a=e.replace(/\s{1,}/g," ").replace(/\{/g,"{~::~").replace(/\}/g,"~::~}~::~").replace(/\;/g,";~::~").replace(/\/\*/g,"~::~/*").replace(/\*\//g,"*/~::~").replace(/~::~\s{0,}~::~/g,"~::~").split("~::~"),i=a.length,f=0,h="",b=0,c=d?k(d):this.shift,b=0;b<i;b++)/\{/.exec(a[b])?h+=c[f++]+a[b]:/\}/.exec(a[b])?h+=c[--f]+a[b]:(/\*\\/.exec(a[b]),h+=c[f]+a[b]);return h.replace(/^\n{1,}/,
"")};i.prototype.sql=function(e,d){for(var a=e.replace(/\s{1,}/g," ").replace(/\'/ig,"~::~'").split("~::~"),i=a.length,f=[],h=0,b=this.step,c=0,j="",g=0,l=d?k(d):this.shift,g=0;g<i;g++)f=g%2?f.concat(a[g]):f.concat(a[g].replace(/\s{1,}/g," ").replace(/ AND /ig,"~::~"+b+b+"AND ").replace(/ BETWEEN /ig,"~::~"+b+"BETWEEN ").replace(/ CASE /ig,"~::~"+b+"CASE ").replace(/ ELSE /ig,"~::~"+b+"ELSE ").replace(/ END /ig,"~::~"+b+"END ").replace(/ FROM /ig,"~::~FROM ").replace(/ GROUP\s{1,}BY/ig,"~::~GROUP BY ").replace(/ HAVING /ig,
"~::~HAVING ").replace(/ IN /ig," IN ").replace(/ JOIN /ig,"~::~JOIN ").replace(/ CROSS~::~{1,}JOIN /ig,"~::~CROSS JOIN ").replace(/ INNER~::~{1,}JOIN /ig,"~::~INNER JOIN ").replace(/ LEFT~::~{1,}JOIN /ig,"~::~LEFT JOIN ").replace(/ RIGHT~::~{1,}JOIN /ig,"~::~RIGHT JOIN ").replace(/ ON /ig,"~::~"+b+"ON ").replace(/ OR /ig,"~::~"+b+b+"OR ").replace(/ ORDER\s{1,}BY/ig,"~::~ORDER BY ").replace(/ OVER /ig,"~::~"+b+"OVER ").replace(/\(\s{0,}SELECT /ig,"~::~(SELECT ").replace(/\)\s{0,}SELECT /ig,")~::~SELECT ").replace(/ THEN /ig,
" THEN~::~"+b+"").replace(/ UNION /ig,"~::~UNION~::~").replace(/ USING /ig,"~::~USING ").replace(/ WHEN /ig,"~::~"+b+"WHEN ").replace(/ WHERE /ig,"~::~WHERE ").replace(/ WITH /ig,"~::~WITH ").replace(/ ALL /ig," ALL ").replace(/ AS /ig," AS ").replace(/ ASC /ig," ASC ").replace(/ DESC /ig," DESC ").replace(/ DISTINCT /ig," DISTINCT ").replace(/ EXISTS /ig," EXISTS ").replace(/ NOT /ig," NOT ").replace(/ NULL /ig," NULL ").replace(/ LIKE /ig," LIKE ").replace(/\s{0,}SELECT /ig,"SELECT ").replace(/\s{0,}UPDATE /ig,
"UPDATE ").replace(/ SET /ig," SET ").replace(/~::~{1,}/g,"~::~").split("~::~"));i=f.length;for(g=0;g<i;g++)c-=f[g].replace(/\(/g,"").length-f[g].replace(/\)/g,"").length,/\s{0,}\s{0,}SELECT\s{0,}/.exec(f[g])&&(f[g]=f[g].replace(/\,/g,",\n"+b+b+"")),/\s{0,}\s{0,}SET\s{0,}/.exec(f[g])&&(f[g]=f[g].replace(/\,/g,",\n"+b+b+"")),/\s{0,}\(\s{0,}SELECT\s{0,}/.exec(f[g])?(h++,j+=l[h]+f[g]):/\'/.exec(f[g])?(c<1&&h&&h--,j+=f[g]):(j+=l[h]+f[g],c<1&&h&&h--);return j=j.replace(/^\n{1,}/,"").replace(/\n{1,}/g,
"\n")};i.prototype.xmlmin=function(e,d){return(d?e:e.replace(/\<![ \r\n\t]*(--([^\-]|[\r\n]|-[^\-])*--[ \r\n\t]*)\>/g,"").replace(/[ \r\n\t]{1,}xmlns/g," xmlns")).replace(/>\s{0,}</g,"><")};i.prototype.jsonmin=function(e){return typeof JSON==="undefined"?e:JSON.stringify(JSON.parse(e),null,0)};i.prototype.cssmin=function(e,d){return(d?e:e.replace(/\/\*([^*]|[\r\n]|(\*+([^*/]|[\r\n])))*\*+\//g,"")).replace(/\s{1,}/g," ").replace(/\{\s{1,}/g,"{").replace(/\}\s{1,}/g,"}").replace(/\;\s{1,}/g,";").replace(/\/\*\s{1,}/g,
"/*").replace(/\*\/\s{1,}/g,"*/")};i.prototype.sqlmin=function(e){return e.replace(/\s{1,}/g," ").replace(/\s{1,}\(/,"(").replace(/\s{1,}\)/,")")};window.vkbeautify=new i})();